<?php


namespace AthomeSolution\ImportBundle\Services\ConfigSpecification;


use Doctrine\ORM\EntityManagerInterface;

/**
 * Class DatabaseSpecification
 * @package AthomeSolution\ImportBundle\Services\ConfigSpecification
 */
class DatabaseSpecification extends AbstractConfigSpecification
{
    /**
     * @var EntityManagerInterface
     */
    private $entityManager;

    /**
     * DatabaseSpecification constructor.
     * @param EntityManagerInterface $entityManager
     */
    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
    }

    /**
     * @param array $data
     * @param array $objects
     */
    public function support(array $data, array &$objects)
    {
        parent::support($data, $objects); // TODO: Change the autogenerated stub
    }

    /**
     * @param array $data
     * @param array $objects
     * @return boolean
     */
    public function execute(array $data, array &$objects)
    {
        try {
            foreach ($objects as $object) {
                $this->entityManager->persist($object);
            }
        } catch (\Exception $exception) {
            return false;
        }

        return true;
    }
}