parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        mapping_types:
            _text: string
        types:
            geography:
                class: 'Jsor\Doctrine\PostGIS\Types\GeographyType'
                commented: false
            geometry:
                class: 'Jsor\Doctrine\PostGIS\Types\GeometryType'
                commented: false
            raster:
                class: 'Jsor\Doctrine\PostGIS\Types\RasterType'
                commented: false

        # configure these for your database server
        driver: 'pdo_pgsql'
        server_version: '11'

        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: false
        dql:
            string_functions:
                ST_Centroid: Jsor\Doctrine\PostGIS\Functions\ST_Centroid
                ST_X: Jsor\Doctrine\PostGIS\Functions\ST_X
                ST_Y: Jsor\Doctrine\PostGIS\Functions\ST_Y
        mappings:
            App:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Resources/config/doctrine'
                prefix: 'App\Entity'
                alias: App
#            import_bundle:
#                type: xml
#                dir: '%kernel.project_dir%/src/Resources/config/import_bundle'
#                prefix: 'AthomeSolution\ImportBundle'
#                is_bundle: false
#            user_bundle:
#                type: xml
#                dir: '%kernel.project_dir%/vendor/athome-solution/user-bundle/src/Resources/config/doctrine'
#                prefix: 'Athome\UserBundle\Model'
#                is_bundle: false


