imports:
    - { resource: '@AthomeSolutionImportBundle/Resources/config/services.yaml'}
# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
        bind:
            $exportDir: '%export_file_path%'
            $importDir: '%import_file_path%'
            $projectDir: '%kernel.project_dir%'
            $inseeImportDir: '%insee_import_file_path%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    Jsor\Doctrine\PostGIS\Event\ORMSchemaEventSubscriber:
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    ignore_view_subscriber:
        class: App\EventSubscriber\DoctrineViewsIgnoreListener
        autowire: true
        tags:
            - {name: doctrine.event_listener, event: postGenerateSchema }
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Services\ImportLogService:
        arguments:
            - '@App\Manager\DataLineManager'
            - '%import_file_path%'
            - '@App\Manager\ImportLogManager'
            - '@App\Repository\ImportLogRepository'
            - '@kernel'

    # Config specifications

    App\Services\ConfigSpecifications\DataColumnSpecification:
        tags:
            - { name: 'athome_import.config_specification', priority: 1 }

    App\Services\ConfigSpecifications\DataTextSpecification:
        tags:
            - { name: 'athome_import.config_specification', priority: 2 }

    App\Services\ConfigSpecifications\DataFloatSpecification:
        tags:
            - { name: 'athome_import.config_specification', priority: 3 }

    App\Services\ConfigSpecifications\DataIntSpecification:
        tags:
            - { name: 'athome_import.config_specification', priority: 4 }

    App\Services\ConfigSpecifications\DataPercentSpecification:
        tags:
            - { name: 'athome_import.config_specification', priority: 5 }

    App\Services\ConfigSpecifications\DataDateSpecification:
        tags:
            - { name: 'athome_import.config_specification', priority: 6 }

    App\Services\ConfigSpecifications\DataYesNoSpecification:
        tags:
            - { name: 'athome_import.config_specification', priority: 7 }

    App\Services\ConfigSpecifications\SirenRootSpecification:
        tags:
            - { name: 'athome_import.config_specification', priority: 8 }

    App\Services\ConfigSpecifications\SirenCarrierSpecification:
        tags:
            - { name: 'athome_import.config_specification', priority: 9 }

    App\Services\ConfigSpecifications\PersistSpecification:
        tags:
            - { name: 'athome_import.config_specification', priority: 10 }
