<?php


namespace AthomeSolution\ImportBundle;


use AthomeSolution\ImportBundle\DependencyInjection\AthomeSolutionImportBundleExtension;
use AthomeSolution\ImportBundle\DependencyInjection\Compiler\ImportBundleCompilerPass;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\HttpKernel\Bundle\Bundle;
use Doctrine\Bundle\DoctrineBundle\DependencyInjection\Compiler\DoctrineOrmMappingsPass;

/**
 * Class AthomeSolutionImportBundle
 * @package AthomeSolution\ImportBundle
 */
class AthomeSolutionImportBundle extends Bundle
{
    /**
     * Returns the bundle's container extension.
     *
     * @return AthomeSolutionImportBundleExtension The container extension
     *
     */
    public function getContainerExtension()
    {
        return new AthomeSolutionImportBundleExtension();
    }

    /**
     * {@inheritdoc}
     *
     * This method can be overridden to register compilation passes,
     * other extensions, ...
     */
    public function build(ContainerBuilder $container)
    {
        parent::build($container); // TODO: Change the autogenerated stub

        $container->addCompilerPass(new ImportBundleCompilerPass());
        $this->addRegisterMappingsPass($container);
    }

    /**
     * @param ContainerBuilder $container
     */
    private function addRegisterMappingsPass(ContainerBuilder $container)
    {
        $mappings = [
            realpath(__DIR__ . '/Resources/config/doctrine') => 'AthomeSolution\ImportBundle\Entity',
        ];

        $container->addCompilerPass(DoctrineOrmMappingsPass::createXmlMappingDriver($mappings));
    }
}